version: '3'

networks:
  wordpress:

services:
  site:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./wordpress:/usr/share/nginx/html:delegated
    depends_on:
      - php
      - mariadb
    networks:
      - wordpress

  mariadb:
    image: mariadb:10.7.3
    container_name: mariadb
    hostname: wordpress_db_host
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_DATABASE: wp
      MARIADB_USER: wp
      MARIADB_PASSWORD: secret
      MARIADB_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mariadb
    networks:
      - wordpress
    volumes:
      - wordpress-db-data:/var/lib/mysql
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php
    volumes:
      - ./wordpress:/usr/share/nginx/html:delegated
    networks:
      - wordpress

  wp:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: wp
    entrypoint: ['wp', '--allow-root']
    environment:
      WORDPRESS_DB_HOST: wordpress_db_host
      WORDPRESS_DB_NAME: wp
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: secret
    volumes:
      - ./wordpress:/usr/share/nginx/html:delegated
    networks:
      - wordpress
volumes:
  wordpress-db-data: